title: Full Stack Developer The Sweet Excursion :rocket:
author: Marquise Piton
email: pitonmarquise@gmail.com
description: >
  I will document weekly of my journey through the Awesome Inc. bootcamp to becoming a full stack developer.
# social links

github_username:  marquisepiton

show_excerpts: true 
theme: jekyll-theme-cayman






  


