title: Journey to Becoming a Full Stack Developer Blog
author: Marquise Piton
description: I will document weekly of my journey through the Awesome Inc. bootcamp to becoming a full stack developer.
email: pitonmarquise@gmail.com
theme: jekyll-theme-cayman







  


