title: Full Stack Developer
author: Marquise Piton
email: pitonmarquise@gmail.com
description: >
I will document weekly of my journey through the Awesome Inc. bootcamp to becoming a full stack developer.
[](https://github.com/marquisepiton/Journey-to-Becoming-a-Full-Stack-Developer-Blog/edit/main/blog.md)
# social links
github_username:  marquisepiton
show_excerpts: true 
theme: jekyll-theme-cayman






  


