
title: jekyll-theme-cayman
author: Marquise Piton
email: pitonmarquise@gmail.com
description: >
  I will document weekly of my journey through the Awesome Inc. bootcamp to becoming a full stack developer.
# social links
instagram_username: marquisepiton
github_username:  marquisepiton

show_excerpts: true 
theme: jekyll-theme-cayman






  


