theme: jekyll-theme-cayman
title: Journey to Becoming a Full Stack Developer Blog 
description: In this project, I will document weekly of my journey through the Awesome Inc. bootcamp to becoming a full stack developer.

